let taco = {
    "seasoning": {
        "url": "https://raw.github.com/sinker/tacofancy/master/seasonings/universal_taco_seasoning.md",
        "recipe": "Universal Taco Seasoning\n========================\n\nI got tired of buying packets of store-bought taco seasoning, so I experimented with various spices and ratios until I landed on this recipe. I keep a jar of it in the cupboard at all times.\n\n* 6 tbsp chili powder\n* 4 tbsp cumin\n* 4 tbsp corn starch\n* 3 tbsp onion powder\n* 1 tbsp salt\n* 1 tbsp garlic powder\n* 4 tsp oregano (Mexican oregano, if you've got it)\n* 2 tsp crushed red pepper\n\nCombine in Mason jar and shake well to combine.\n\nThis mix works well for chicken, pork and beef, destined for the grill, oven, slow cooker or stovetop. You could tweak it a bit to target a specific meat, but I like to have a base, universal mix around. Makes it super easy to turn leftover anything into delicious taco filling: Just chop up whatever it is, toss it into a skillet, sprinkle generously with seasoning, then add a bit of water and simmer to impart flavor.\n\ntags: vegetarian, vegan\n",
        "name": "Universal Taco Seasoning",
        "slug": "universal_taco_seasoning"
    },
    "shell": {
        "url": "https://raw.github.com/sinker/tacofancy/master/shells/Fresh_corn_tortillas.md",
        "recipe": "Fresh Corn Tortillas\n===================\n\nThis is the only way to go. So worth it. Makes roughly 15 tortillas.\n\n* 1 3/4 cups masa harina\n* 1 1/8 cups water\n\n1. In a medium bowl, mix together masa harina and hot water until thoroughly combined. Turn dough onto a clean surface and knead until pliable and smooth. If dough is too sticky, add more masa harina; if it begins to dry out, sprinkle with water. Cover dough tightly with plastic wrap and allow to stand for 30 minutes.\n2. Preheat a cast iron skillet or griddle to medium-high.\n3. Divide dough into 15 equal-size balls. Using a tortilla press (or a rolling pin), press each ball of dough flat between two sheets of wax paper (plastic wrap or a freezer bag cut into halves will also work).\n4. Place tortilla in preheated pan and allow to cook for approximately 30 seconds, or until browned and slightly puffy. Turn tortilla over to brown on second side for approximately 30 seconds more, then transfer to a plate. Repeat process with each ball of dough. Keep tortillas covered with a towel to stay warm and moist (or a low temp oven) until ready to serve.\n\ntags: vegetarian, vegan\n",
        "name": "Fresh Corn Tortillas",
        "slug": "fresh_corn_tortillas"
    },
    "condiment": {
        "url": "https://raw.github.com/sinker/tacofancy/master/condiments/chile_de_arbol_sauce.md",
        "recipe": "Salsa de chile de \u00e1rbol\n=======================\n\nThis is a go-to taco sauce in western Mexico and probably elsewhere. You can\nmix and match the techniques in the two variants presented here, and substituting\nor adding chiles is a ramp onto the combinatorial superhighway of Mexican food and\ncan demystify the salsa bar at the local taquer\u00eda.\n\n# Red\n\n* dried whole *chiles de \u00e1rbol*\n* tomatoes\n* onion\n* *optionally*, garlic\n\nTake between .3 and 1 chiles per tomato, remove the stems and put them in a\nsaucepan with a tablespoon or two of oil (olive, soy, etc.) The pan and oil should be very\nhot and the chiles should seem to be at risk of burning. Rotate the\nchiles around and let them get dark brown to black without actually burning them \u2014\nthis can happen quickly, which is good because your eyes, nose, and lungs\nmay reach their maximum vaporized chile tolerance during this step.\n\nAdd a bunch of chopped onion and garlic and lower the heat. Cut the tomatoes\nin half and throw them in with salt to taste. Cook until the tomatoes look stewed.\nIf you have one of those blender wands that you can put directly in a saucepan,\nyou can blend everything now (you may end up making this sauce frequently enough\nto justify the purchase of a blender wand.) Otherwise wait until the mixture\nis not hot and blend it in a standard blender.\n\n# Green\n\n* dried whole *chiles de \u00e1rbol*\n* green tomatillos\n* onion\n* cilantro\n\nTake between .1 and .5 chiles per tomatillo, remove the stems and put them in a bare, hot saucepan.\nToast the chiles without oil until they are dark. Add halved or quartered tomatillos, salt, and a\ntablespoon or two of water to prevent burning the chiles before the tomatillos release\ntheir juices. When the mixture has cooked for as long as you can stand to wait, remove\nthe heat and let it cool. Blend and place in a little salsa bowl and heap with finely\nchopped onion and cilantro.\n\nOne non-obvious little point is that skipping the oil in the chile roasting-toasting\nstep seems to increase the spiciness of the final product.\n\ntags: vegetarian\n",
        "name": "Salsa de chile de \u00e1rbol",
        "slug": "salsa_de_chile_de_arbol"
    },
    "mixin": {
        "url": "https://raw.github.com/sinker/tacofancy/master/mixins/traditional_taco_mixins.md",
        "recipe": "Traditional Taco Mixins\n(makes about 20 servings)\n\n- 1 (16 ounce) container sour cream\n- 1/4 head iceberg lettuce (rinsed, dried, shredded)\n- 1 cup shredded cheddar cheese\n- 3 diced tomatoes\n- 1 (2.25 ounce) can black olives, drained\n\nAdd ingredients to tacos in layers. \n\ntags: vegetarian\n\n",
        "name": "Traditional Taco Mixins",
        "slug": "traditional_taco_mixins"
    },
    "base_layer": {
        "url": "https://raw.github.com/sinker/tacofancy/master/base_layers/battered_catfish.md",
        "recipe": "North Carolina Battered Catfish\n===============================\n\nDo it right and [stick your arm down a catfish hole in the muddy waters of a north carolina pond](http://www.youtube.com/watch?v=zc_huHb4PMc), take that sucker home at serve it up to your friends and family on some corn tortilas\n\n* 1 cup all-purpose flour\n* 1 cup cornmeal\n* 1 tablespoon baking powder\n* 1 tablespoon kosher salt\n* 1/2 teaspoon cayenne pepper\n* 1 (12-ounce) bottle amber beer\n* 4 (6-ounce) catfish fillets\n* 1 tablespoon salt\n* 1 tablespoon cracked black pepper\n* 2 tablespoons granulated garlic\n* 1 lemon, juiced\n\nPreheat a deep-fryer to 350 degrees Fahrenheit.\n\nIn a large bowl, add the flour, cornmeal, baking powder, salt and cayenne and whisk to combine. Whisk in the beer, being sure to remove any lumps.\n\nCut the catfish fillets in half lengthwise to make 2 strips. If desired, cut into bite-sized pieces. In a small bowl add the salt, pepper and granulated garlic. Season the fillets with the salt mixture.\n\nDip each strip in the beer batter and add to the fryer, a few at a time, moving them around so they don't stick. Fry until brown and crispy, about 3 to 4 minutes. Remove from the fryer to a serving platter. Repeat with the remaining fillets and season the fish with lemon juice. Cut them up into taco size portions and show your friends how amazing your catch tastes.\n",
        "name": "North Carolina Battered Catfish",
        "slug": "north_carolina_battered_catfish"
    }
}
export {taco};